---
- name: create username and public key
  # gather_facts: no 
  hosts: all
  become: true
  become_method: sudo
  user: centos  

  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: no

      generate_ssh_key: true
    - name: Set authorized key taken from file
      authorized_key:
      # generate_ssh_key: true
        user: "{{username}}"
        state: present
        key: "{{ lookup('file', /home/"{{username}}"/.ssh/id_rsa.pub') }}"
        
    # - name: password
    #   prompt: "What is your password?"
  tasks:
    - debug:
        msg: 'Logging in as {{ username }}' 

    - name: add users
      user: 
        name: "{{username}}"
        state: present
  

    