---
- name: Install wordpress on CentOS 7 
  # gather_facts: no 
  hosts: localhost
  become: true
  become_method: sudo
  user: centos  
  tasks:
    - name: add users
      user: 
        name: "{{username}}"
        state: present
        